name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/checkout@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test
---
name: CD
on:
   push:
      branches: ["master", "main"]
permissions:
   contents: read
   packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/log-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB.TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.respository }}/app:latest
---
name: Deployment
on: workflow_dispatch
jobs:
  deploy:
     runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: echo "Deploying application..."
      - name: Restaring
        run: echo "Restarting server..."

